### ISSUE TITLE
Feature 1: User can create an account

### ISSUE THREAD

**Issue by dennis-pnguyen** [dennis-pnguyen/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account on the app
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- user can create an account to login/logout
- This will allow the user to add games to a wishlist or leave a review

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-09-29 at 3 38 03 PM](https://github.com/dennis-pnguyen/final-project/assets/122412863/45726099-bae8-4cf2-a173-53ffb863cf15)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server.js` to insert user inputs into the database
- [x] Insert statements for user credentials
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a controlled form component to allow the user to create their account
- [ ] Update component to take multiple inputs
- [ ]  

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by dennis-pnguyen** [comment]
Completed user registration form and functionality
